### ISSUE TITLE
feat: PocketTube/NewPipe-like Channel Grouping feature?

### ISSUE THREAD

**Issue by RoonMoonlight** [YT-Advanced/ReX-patches#105]
### Application

YouTube

### Feature description

Add the channel group customization features similar to [NewPipe](https://newpipe.net/)'s channel grouping and [PocketTube](https://pockettube.io/) extension, which allows you to sort some channels into groups.

### Motivation

I have been annoying that YouTube does not officially have channel category customization like [NewPipe](https://newpipe.net/) and [PocketTube](https://pockettube.io/), and would like to see some similar feature that allows you to customize the category client-side. I mainly use it to categorize some of channels for channel genres.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by RoonMoonlight** [comment]
@YT-Advanced Again? Closing without even stating the reason?

Why

**Comment by YT-Advanced** [comment]
Ah I closed all issues because inotia released RVX and I don't have any reason to keep these issues
