### ISSUE TITLE
feat (YouTube): Ability to hide redundant text in Settings page.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#109]
### Application

YouTube

### Feature description

In the Settings page, only 3 useful options are there (RVX Settings, RYD Settings & SB Settings).

The remaining are just redundant text and nobody even opens them.

So, please add the ability to hide them.

If you cannot put it on priority right now, at least keep the issue open please.
![291025602-04f76e60-c634-4edd-b8b6-de171b7b9f9e](https://github.com/YT-Advanced/ReX-patches/assets/91815107/a984f632-8348-4db1-bc49-3dc2095d0292)

### Motivation

Explained in Feature Description section.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Kuddus73** [comment]
Is this feature implemented?

**Comment by Aryan-Chauhan** [comment]
> Is this feature implemented?

I requested https://github.com/YT-Advanced/ReX-patches/issues/116 , so that's why I closed this.

But none of these issues are implemented yet.
