### ISSUE TITLE
feat (YT Music): Ability to hide "Episodes for later".

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#113]
### Application

YouTube

### Feature description

Kindly add the ability to hide "Episodes for Later" in Library.
![Screenshot_2024-01-28-14-51-47-55_0eaaacfb1e02f862bb18505a09b95933](https://github.com/ReVanced/revanced-patches/assets/91815107/b3f08e28-80a0-4656-a7fb-ac577a026b00)

### Motivation

Many people only use the RVX Music app for listening to music & never listen to podcasts. So, it will provide a better design for them.

If it's not too time-consuming, kindly look into it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
https://github.com/YT-Advanced/ReX-patches/issues/97
