### ISSUE TITLE
feat (YT) : Hide Join button from a channel's homepage.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#114]
### Application

YouTube

### Feature description

Many channels have a Join button next to the Subscribe button. But many users are not interested in joining their memberships. So, kindly look into hiding it.
![Screenshot_2024-01-28-15-07-21-10_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/7958ce4d-1d6d-44dc-8111-2d8cdf31cc8a)

### Motivation

1. People literally visit channel homepages 30-40 times a day. Even if they visit 10 times, that's considerable.
2. It can already be hidden in video player page, so implementing this feature will be a great enhancement.

Thanks!

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
|button.eml$Join
