### ISSUE TITLE
suggestion: Small improvement in "Append video quality".

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#115]
### Application

YouTube

### Suggestion description

The maximum resolution of this video is 2160p. So, I'm requesting that it should show "2160p/2160p" or "2160p:2160p" instead of "2160p" only.

Basically, I'm requesting for "Current quality/Max available quality"

Reason: Sometimes, 2160p videos start playing at 1080p or 1440p randomly, even though video quality is set to 2160p. So, to avoid opening flyout menu again and again for confirmation, this can be implemented for user's convenience.
![272142776-f414be5d-cb77-4616-baa6-c94a26752b27](https://github.com/YT-Advanced/ReX-patches/assets/91815107/54d1de60-39ac-49b3-bf3e-79e092ccfff0)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
You can use Overided Speed, isn't it ?

**Comment by YT-Advanced** [comment]
> > You can use Overided Speed, isn't it ?
> 
> Bro, what's Overided Speed, and how is it related to this suggestion?
> 
>  Can you explain?

In the Settings --> Video, we have an option named "Default Video Speed"

**Comment by Aryan-Chauhan** [comment]
> > > You can use Overided Speed, isn't it ?
> > 
> > Bro, what's Overided Speed, and how is it related to this suggestion?
> > 
> >  Can you explain?
> 
> In the Settings --> Video, we have an option named "Default Video Speed"

Bruh, this request is not the playback speed.

Please read the issue again.

**Comment by YT-Advanced** [comment]
Ah my mistake, it should be "Default Video Quality"

**Comment by Aryan-Chauhan** [comment]
> Ah my mistake, it should be "Default Video Quality"

Yes.

If a video has all qualities available, and I'm playing 720p version of that video, then it should show like this:

720p / 2160p

or

720p : 2160p

This is what I was requesting.

**Comment by YT-Advanced** [comment]
I know, but your reason is invaild:
> Reason: Sometimes, 2160p videos start playing at 1080p or 1440p randomly, even though video quality is set to 2160p. So, to avoid opening flyout menu again and again for confirmation, this can be implemented for user's convenience.

**Comment by Aryan-Chauhan** [comment]
> I know, but your reason is invaild:
> > Reason: Sometimes, 2160p videos start playing at 1080p or 1440p randomly, even though video quality is set to 2160p. So, to avoid opening flyout menu again and again for confirmation, this can be implemented for user's convenience.

Yes, in latest patches, quality latching is working fine, but still it will provide useful information to the user about the video, without opening flyout menu.
