### ISSUE TITLE
feat(YT): Directly open RVX Settings when tapped on Settings icon.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#116]
### Application

YouTube

### Feature description

In the top right corner of You tab, there is a Settings icon. So, I'm requesting for a patch that directly opens ReVanced Settings when you tap on it. If implemented, the following obstructions can be avoided:
1. General
2. Account
3. Data saving
4. Auto-play
5. Video quality preferences
6. Background and downloads
7. Watch on TV
8. Manage all history
9. Your data in YouTube
10. Privacy
11. Try experimental new features
12. Purchases and memberships
13. Billing and payments
14. Notifications
15. Connected apps
16. Live chat
17. Captions
18. Accessibility
19. About
![Screenshot_2024-02-20-23-30-58-66_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/22339829-1047-45d5-aba3-a59c9100aeb4)

### Motivation

I have minimal coding knowledge, but this seems pretty easy for Alireza or inotia00 to implement, since they've already implemented much more complex features in the past.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
So how you can change RVX Settings

**Comment by Aryan-Chauhan** [comment]
> So how you can change other Settings

For people who are interested in changing stock YT settings, they should keep this patch disabled.

This patch will be for people who want nothing to do with stock YT app settings.

**Comment by Aryan-Chauhan** [comment]
Yooo!

Can you reopen this please? 🙂
