### ISSUE TITLE
feat: Add Ability To Disable Short Audio Focus Change/Calls

### ISSUE THREAD

**Issue by AbakNacchan** [YT-Advanced/ReX-patches#121]
### Application

YouTube

### Feature description

Kindly add ability to disable `short audio focus change or temporary pause` when there's notification or call.

### Motivation

This feature is needed so we can watch anything without annoying temporary pause when there's a message or any notification that affect our experience.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Can you share a video how it look like

**Comment by AbakNacchan** [comment]
I'm afraid I couldn't share any video, but this is existing feature on Poweramp with the very same name. So when there's notification, the audio when we're watching YouTube will not paused/lowered.
