### ISSUE TITLE
bug (YT) : Hide Trending Searches isn't working.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#123]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT v19.02.39

### Bug description

![Screenshot_2024-02-27-07-00-00-43_f22faf49515899f9781ec174a4d85388](https://github.com/YT-Advanced/ReX-patches/assets/91815107/60ad37c4-9226-4286-8326-2e07ba653605)

### Error logs

```shell
No logs.
```

### Solution

It should start working again.

### Additional context

Nope.

### Device Environment

Realme 7 Pro.

Android 12.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
It is not trending searches
![image](https://github.com/YT-Advanced/ReX-patches/assets/70064328/f1718380-0d0c-4249-bf3a-91228e0396f2)
