### ISSUE TITLE
feat (YT) : Ability to hide Recommended Searches.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#124]
### Application

YouTube

### Feature description

Please add the ability to hide Recommended Searches.
![Screenshot_2024-02-27-07-00-00-43_f22faf49515899f9781ec174a4d85388](https://github.com/YT-Advanced/ReX-patches/assets/91815107/afd4e331-81b9-42e3-880b-d7bcb2464d9f)

### Motivation

It will complement "Hide Trending Searches" and also provide a cleaner look on search page.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
nah I have explained in RVX Chat. When you hide Recommended Searches, it accidentally hides suggested content every time you typing something to search

**Comment by Aryan-Chauhan** [comment]
> nah I have explained in RVX Chat. When you hide Recommended Searches, it accidentally hides suggested content every time you typing something to search

Actually, I won't care if both are hidden.

Now OK?
