### ISSUE TITLE
bug:  In search

### ISSUE THREAD

**Issue by MANCrimSon** [YT-Advanced/ReX-patches#126]
### Type

Cosmetic

### Tools used

CLI

### Application

YT: 19.02.39, YT-Advanced (ReX) v2.220.7
![photo_2024-02-27_20-13-22](https://github.com/YT-Advanced/ReX-patches/assets/93052479/df8faa14-4e80-4662-bf7c-144acfd5b6ac)

### Bug description

Searches appeared in my history that I never entered.
Moreover, I have search history turned off.

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Same issue here.

**Comment by YT-Advanced** [comment]
#124
