### ISSUE TITLE
feat (YT) : Ability to hide Key Concepts.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#127]
### Application

YouTube

### Feature description

Kindly add the ability to hide Key Concepts.
Video link: https://youtu.be/86VUqcXo8Sc
![Screenshot_2024-02-28-10-09-13-02_f22faf49515899f9781ec174a4d85388](https://github.com/YT-Advanced/ReX-patches/assets/91815107/9ad3216a-b515-4202-ad64-e87c0df16fb8)

### Motivation

These are auto-generated stuff by YT, and I've noticed that 80% of the times, they are inaccurate, hence they should be hidden away.

Plus, it will be a nice little addition to the plethora of hiding options for Description.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
It is not there, in my side. However, do you know how to debug. If not, feel free to inbox me

**Comment by Aryan-Chauhan** [comment]
> It is not there, in my side. However, do you know how to debug. If not, feel free to inbox me

I enabled "Hide Chapters from Description" and realized that it can also hide Key Concepts.

Hence, closing this issue as solved.
