### ISSUE TITLE
bug: Download button in action bar of YTM not working

### ISSUE THREAD

**Issue by TiLopes** [YT-Advanced/ReX-patches#128]
### Type

Other

### Tools used

rvx-builder

### Application

YouTube Music v6.41.54

### Bug description

Pressing the download button in the action bar does not pop up YTDlnis. I have enabled the hook download option.

### Additional context

The builds I got are from this repo (which automatically builds when there's a new release through github actions): https://github.com/revanced-apks/build-apps/releases

### Device Environment

Android 14, One Ui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
@TiLopes Right now you can temporary fix it by spoof the app version to `v6.39.50`

**Comment by selfmusing** [comment]
> @TiLopes Right now you can temporary fix it by spoof the app version to `v6.39.50`

🌚 It still works fine even on v6.41.58 ( at least for me )

https://github.com/YT-Advanced/ReX-patches/assets/109387456/fd06bd5e-22cb-43f0-8903-da37fccbc854


![Screenshot_20240307-154521_YouTube_Music](https://github.com/YT-Advanced/ReX-patches/assets/109387456/dd99726f-6d02-46b1-9eff-b901a8796a17)
