### ISSUE TITLE
bug: Crash on startup on YouTube v19.07.40

### ISSUE THREAD

**Issue by blacktornadog7** [YT-Advanced/ReX-patches#129]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.07.40

### Bug description

Crash on startup due to latest update: 
ReX-patches v2.220.7
ReX-integrations v0.145.2

### Error logs

```shell
https://gist.github.com/blacktornadog7/d38a70268790525f0834c90813afebfc
```

### Device Environment

Android 13 oneui 5.1
and also on: Android 14 oneui 6

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
You are patching unsupported version
