### ISSUE TITLE
feat: Hide shorts on related videos section

### ISSUE THREAD

**Issue by RoonMoonlight** [YT-Advanced/ReX-patches#132]
### Application

YouTube

### Feature description

Would be great if there is option to hide shorts on related videos section.

### Motivation

Same as related videos, sometimes they show unrelated and controversy shorts, which makes me uncomfortable. Would be great if there is option to hide it on related videos section.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Uhm, but the `hide shorts shelf` options did that

**Comment by RoonMoonlight** [comment]
> Uhm, but the `hide shorts shelf` options did that

That also hides the Shorts on Subscription page, the thing I meant is the feature that only hides Shorts on recommended video section

@YT-Advanced Also stop closing and archiving the repo for no reason, please (or please otherwise state the reason why it was archived before doing so)

**Comment by YT-Advanced** [comment]
Hmm if I do this patch, it may have some weird behavior 😭
