### ISSUE TITLE
bug: Comment Replies Bug

### ISSUE THREAD

**Issue by jacobh12349** [YT-Advanced/ReX-patches#135]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.02.39

### Bug description

I just started using ReX today, and I noticed this bug with comment replies.
There's a big blank spot above and below the replies of comments on my ReX app that is patched with the ReX patches and the ReX integrations.
It might even just be some setting that I need to change in the revanced extended settings, but I don't know though.

![Screenshot_20240301_025110_ReVanced Extended](https://github.com/YT-Advanced/ReX-patches/assets/30378473/17e20dba-bd6b-46d1-9e1e-17d3f2bb4a24)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by jacobh12349** [comment]
Nvm, it's not happening anymore today now, it was only happening yesterday

**Comment by jacobh12349** [comment]
It could actually only happen on certain videos though, I'll check that video that it happened on again now

**Comment by jacobh12349** [comment]
> It could actually only happen on certain videos though, I'll check that video that it happened on again now

No, it's not happening on that video anymore, so it was just only happening yesterday for some reason

**Comment by jacobh12349** [comment]
> Nvm, it's not happening anymore today now, it was only happening yesterday

Nvm again, it just happened again now, it might just happen randomly sometimes.

![Screenshot_20240302_010818_ReVanced Extended](https://github.com/YT-Advanced/ReX-patches/assets/30378473/4111eebf-ab7b-43a6-8f49-5f685d31d8ca)

**Comment by YT-Advanced** [comment]
@jacobh12349 Can you turn off settings one by one to check it. Thanks a lot
