### ISSUE TITLE
bug: ReX UI doesn't look like YouTube it's looking wierd

### ISSUE THREAD

**Issue by whitedevilcodez** [YT-Advanced/ReX-patches#136]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.02.39

### Bug description

UNKNOWN Searches and The Yt home page looks wierd.
![IMG-20240301-WA0007](https://github.com/YT-Advanced/ReX-patches/assets/89518552/918b0b0f-ab32-4f9a-8d9d-4946c65c14e1)
![IMG-20240301-WA0006](https://github.com/YT-Advanced/ReX-patches/assets/89518552/b3883e42-3222-40f2-b728-5ac9aa48fdee)

### Device Environment

Android 14 , HyperOS (OS Version - 1.0.3.0ULUINXM [For poco Users])

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
LMAO, It is a server side issue , not a REX issue !!
BLAME GOOGLE 😭😭😭

**Comment by YT-Advanced** [comment]
Turn on your watch history
