### ISSUE TITLE
Telegram Group or Discord Server

### ISSUE THREAD

**Issue by tiwna16** [YT-Advanced/ReX-patches#138]
### Application

YouTube

### Question description

I can't able to find out any links of Discord Server or Telegram Group in this Repository.
Have you guys any available Telegram Group or Discord Server for YT-Advanced?
If you have,Please share the links with me in the reply section.I would be very thankful.
If not,then please make any one(Or both) of the social media account.It will be very easy to find out about YT-Advanced project & updates.There we can ask or search common queries & Here We will report the bugs or enhancement features.I think,It will be much more cleaner experience for both users and developers.
It's a suggestion with request.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Telegram group: https://t.me/ReXgroups
