### ISSUE TITLE
Bug (Reddit): Hide recently visited shelf failed while patching 

### ISSUE THREAD

**Issue by johnnyw94** [YT-Advanced/ReX-patches#142]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Reddit 2024.10.0

### Bug description

![Screenshot_2024-03-05-22-26-48-918_app rvx manager flutter](https://github.com/YT-Advanced/ReX-patches/assets/36622355/b79703c6-af69-4936-848d-f0180f7019f2)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Reddit has reverted back its changes/bug, you can use the latest version of Reddit v2024.12.0 or release before - v2024.11.x.
