### ISSUE TITLE
suggestion (Youtube): Join button is not removed under channel profiles.

### ISSUE THREAD

**Issue by Cast0r-999** [YT-Advanced/ReX-patches#143]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Youtube v19.01.34 (or other versions)
YT-Advanced v2.220.9

### Bug description

Join button under channel profile is not hidden, even when option is turned on. 
*Under video player button is removed correctly.
![Screenshot_2024-03-05-18-38-29-234_app rvx android youtube](https://github.com/YT-Advanced/ReX-patches/assets/162354008/5d2e3b5b-44fd-46d6-b50c-90781929ef33)
![Screenshot_2024-03-05-18-37-31-500_app rvx android youtube_1](https://github.com/YT-Advanced/ReX-patches/assets/162354008/529be68f-d39f-4f7e-901a-6116eab13989)

### Device Environment

Android 10, official MIUI 12.0.1, non-root. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Bruuuh, why do you think that this setting supposed to hide join button in channel profile, setting placed under bottom player category, all settings related to channel profile placed in General > Channel profile

**Comment by Cast0r-999** [comment]
> Bruuuh, why do you think that this setting supposed to hide join button in channel profile, setting placed under bottom player category, all settings related to channel profile placed in General > Channel profile

Then i transfer this to suggestions. I'm surprised, that nobody done it.
