### ISSUE TITLE
bug (Youtube): Long description stuttering while you scroll.

### ISSUE THREAD

**Issue by Cast0r-999** [YT-Advanced/ReX-patches#145]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Tested on every Youtube version from 19.02 to 19.08.
19.01 or lower are unaffected.
This bug migrated from latest inotia00 patches to your fork and still exist.
On video depicted Youtube 19.05.36 & patch v2.220.9

### Bug description

On every version of Youtube, starting from 19.02, long description stutters/laggs/jump when you scroll it.
Example: https://youtube.com/shorts/OQb92NoB4vQ?si=EZDF7AKX7VYrKgG8

### Additional context

Bug existed on latest inotia00 patches.

### Device Environment

Android 10, official MIUI 12.0.1, non-root.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Please check this behaviour in unpatched youtube before saying that this is bug of patch
