### ISSUE TITLE
bug: (YouTube/Tablet mini player): Enabling the Tablet Mini Player reduces the interface to full screen mode.

### ISSUE THREAD

**Issue by ghost** [YT-Advanced/ReX-patches#146]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

YouTube v19.07.40

### Bug description

After turning on the tablet mini player, it affects and changes the interface in full screen mode.
![IMG_20240306_031601_585](https://github.com/YT-Advanced/ReX-patches/assets/55586822/f7aa413e-d66c-4ae9-bbe9-beeba0c0c7e4)
![IMG_20240306_031603_714](https://github.com/YT-Advanced/ReX-patches/assets/55586822/3d2e612e-f7e8-4906-8f24-d56112438def)
![IMG_20240306_031558_816](https://github.com/YT-Advanced/ReX-patches/assets/55586822/ef990a91-0349-440e-b110-7c9aa34054cc)

### Device Environment

Android 14
Evolution X
Redmi Note 8

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
What is the different between these screenshot
