### ISSUE TITLE
Move miscellaneous to the bottom and general to the top

### ISSUE THREAD

**Issue by speedlorenzo12** [YT-Advanced/ReX-patches#147]
### Application

YouTube

### Suggestion description

Since the days of RVX before there were few options and miscellaneous were at the bottom I would prefer that the miscellaneous  settings go to the bottom because it is more convenient and makes more sense
![IMG_20240305_225853](https://github.com/YT-Advanced/ReX-patches/assets/111771663/edcda7f6-9794-4c96-847f-7e0ad7f81bca)

And move general to the top
![IMG_20240305_231106.png](https://github.com/YT-Advanced/ReX-patches/assets/111771663/7523404e-2998-4b36-8090-70ddbc02a7d8)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
@anddea Can you send a PRs

**Comment by anddea** [comment]
> @anddea Can you send a PRs

Sure, later. Should I send only this update of Settings, or all my commits in one PR, or separate them and for each feature create a new PR? Some of features are already open in your PRs, one for clarifying Strings and second for updated Shorts icons.

**Comment by YT-Advanced** [comment]
> Sure, later. Should I send only this update of Settings, or all my commits in one PR, or separate them and for each feature create a new PR? Some of features are already open in your PRs, one for clarifying Strings and second for updated Shorts icons.

Pls create a PR for a feature. Thanks
