### ISSUE TITLE
What do we set in RVX Builder for Cli?

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [YT-Advanced/ReX-patches#148]
### Application

YouTube

### Question description

Using RVX Builder in Termux, what do we set the following values to? 

- `Cli Organization`
- `Cli Sources`

Please forgive me if this has been documented somewhere but I've spent a signicamt amount of time searching everywhere for an answer to this and have come up empty-handed. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Alireza already has his own rvx builder https://github.com/YT-Advanced/rvx-builder

**Comment by misterpyrrhuloxia** [comment]
@girshcatt, thanks for your response. That's exactly what I tried using already but unfortunately isn't working. Just now, I even tried deploying the Docker container through Docker Desktop on Windows and I even tried installing the Windows exe from that repo's Releases and the sources don't seem to be up-to-date:

https://i.imgur.com/ARprJoC.png

Attempting to proceed in spite of those sources gives me this error:
```node
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: You got ratelimited from GitHub
...Completely? What did you even do?
    at getDownloadLink (C:\snapshot\rvx-builder\utils\FileDownloader.js:52:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadFiles (C:\snapshot\rvx-builder\utils\FileDownloader.js:164:26)
    at async updateFiles (C:\snapshot\rvx-builder\wsEvents\updateFiles.js:69:3)
    at async WebSocket.<anonymous> (C:\snapshot\rvx-builder\index.js:176:9)
[builder] Please report this bug here: https://github.com/YT-Advanced/rvx-builder/issues.
```

**Comment by misterpyrrhuloxia** [comment]
I would like to, but the problem is that while his error says to "Please report this but here: https://github.com/YT-Advanced/rvx-builder/issues", going to that page just redirects to here:
https://github.com/YT-Advanced/rvx-builder/pulls
It appears that there is no `Issues` page on his rvx-builder repo.

**Comment by girshcatt** [comment]
i think you can report this bug here, not in builder repo

**Comment by misterpyrrhuloxia** [comment]
Where?

**Comment by girshcatt** [comment]
you can create a bug report in issue page of this repository
