### ISSUE TITLE
question: Released version downgrade?

### ISSUE THREAD

**Issue by pmsobrado** [YT-Advanced/ReX-patches#150]
### Application

YouTube

### Question description

I saw a couple of days that the YT recommended version was 19.0**6**.36, but now is 19.0**5**.36, did something happen? Why this downgrade? I'm just curious, thanks.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AbakNacchan** [comment]
Compatibility and of course stability.
