### ISSUE TITLE
bug (YT Music/`Import/Export settings`): Import/export settings crashes YT music with certain patch selections

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [YT-Advanced/ReX-patches#158]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

v6.42.52 (issue present in v6.41.XX as well)

### Bug description

The `Import/export settings` isn't working for YT Music and needs to be fixed as it currently crashes the YT Music app and doesn't function as intended. The reason behind its failure is due to certain patches dependency to the `import/export settings` option which isn't triggered with my selection of patches.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
It works fine for here , I'm using YTM v6.41.58.
Checkout this video : https://drive.google.com/file/d/17IraVavCCvzC3D0b6SEvklM3n6KvB3bB/view?usp=drivesdk

**Comment by ILoveOpenSourceApplications** [comment]
Found the issue. If the user doesn't include specific patches such as `SponsorBlock, Spoof app version, Change start page, Custom playback speed`, etc the import/export setting crashes. So with my selection of patches, the setting crashes everytime. Patches selected:
```kotlin
Amoled succeeded
Background play succeeded
Bitrate default value succeeded
Certificate spoof succeeded
Custom package name succeeded
Disable auto captions succeeded
Enable black navigation bar succeeded
Enable landscape mode succeeded
Enable minimized playback succeeded
Enable opus codec succeeded
Exclusive audio playback succeeded
Hide channel guidelines succeeded
Hide emoji picker and time stamp succeeded
Hide general ads succeeded
Hide get premium succeeded
Hide navigation bar component succeeded
Hide terms container succeeded
Hide tooltip content succeeded
Microg support succeeded
Remember video quality succeeded
Sanitize sharing links succeeded
Translations succeeded
Settings succeeded
```

**Comment by ILoveOpenSourceApplications** [comment]
@anddea & @YT-Advanced, any idea why it's failing with certain patch selections?

Edit: Also, now it doesn't crash the app but touching the option does nothing.
