### ISSUE TITLE
The purpose of releases.

### ISSUE THREAD

**Issue by taku-nm** [YT-Advanced/ReX-patches#160]
### Application

Other

### Question description

Can you please stop undermining the entire purpose of releases by updating the 2.220.9 release over and over again?
Just release 2.220.10 instead of replacing releases.

What sort of absurd behaviour is this?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
😁 IT IS WHAT IT IS

**Comment by taku-nm** [comment]
> 😁 IT IS WHAT IT IS

explode
