### ISSUE TITLE
bug: GRAY DESCRIPTION IS NOT WORKING.

### ISSUE THREAD

**Issue by DGlmMortal** [YT-Advanced/ReX-patches#164]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

RE𝕏 YT - [ Non-Root ] V19.09.38
![Screenshot_2024-03-19-20-35-23-769-edit_com miui securitycenter](https://github.com/YT-Advanced/ReX-patches/assets/130741447/170fd5a2-1c40-4a49-afee-a781d6a84bde)

### Bug description

Hello sir I am a Non-Root user, GRAY DESCRIPTION features are not working on my phone even after many attempts. Please solve this issue because this feature is very useful for us🥺🙏🏼
I appreciate your work thank you so very much 🙏🏼💖

https://github.com/YT-Advanced/ReX-patches/assets/130741447/a9b1c763-e2cf-43c3-ba14-302b07a933fb

### Solution

Please solve this issue ASAP🙏🏼

### Device Environment

Android 12 , MIUI 13.0.2
![Screenshot_2024-03-19-20-44-11-304-edit_com android settings](https://github.com/YT-Advanced/ReX-patches/assets/130741447/3e62b58f-3e8e-48de-aa59-02919bf5737d)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Latest officially supported by ReX YouTube version is 19.07.40

**Comment by girshcatt** [comment]
Try to turn Spoof app version toggle off

**Comment by YT-Advanced** [comment]
You are using unsupported version

**Comment by DGlmMortal** [comment]
> You are using unsupported version

Which is the supported version?

**Comment by YT-Advanced** [comment]
> > You are using unsupported version
> 
> Which is the supported version?

19.07.xx

**Comment by DGlmMortal** [comment]
> > > You are using unsupported version
> > 
> > 
> > Which is the supported version?
> 
> 19.07.xx

Please give me the link of the supported non-root version apk
