### ISSUE TITLE
question: "MicroG is not found" when I attempt to start Revanced Extended 

### ISSUE THREAD

**Issue by yuukiAme** [YT-Advanced/ReX-patches#166]
### Application

YouTube

### Question description

I patched Youtube with the new v2.220.10 
I downloaded the new [GmsCore](https://github.com/microg/GmsCore) v0.3.1.240913.
I signed in to Google account with microG Settings. 
But when I start the Youtube app (Revanced Extended), the app directs me to Vanced MicroG v0.3.0.234914 and pop up message "MicroG is not found"

Did I miss a step somewhere to use the new patch - v2.220.10?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
You need this gmscore https://github.com/YT-Advanced/GMSCore/releases/latest

**Comment by yuukiAme** [comment]
> You need this gmscore https://github.com/YT-Advanced/GMSCore/releases/latest

I cannot download it for some reason.

![2024_03_26_14_25_11_vivaldi](https://github.com/YT-Advanced/ReX-patches/assets/45681604/f9f7484c-03cb-41e8-9b7f-834c908ce9b8)

**Comment by yuukiAme** [comment]
New problem @girshcatt 
I uninstalled the GMScore v0.3.1 and tried to installed the GMScore from ReX. It won't let me install the microG Services

```
microG Services
App not instaleld as package conflicts with an existing package
```

But I already uninstalled the Vanced MicroG and GMScore from microg. What did I miss?

**Comment by yuukiAme** [comment]
and the latest GMScore v0.3.0.241017 is gone from the [latest release](https://github.com/YT-Advanced/GMSCore/releases/latest)

The latest now is from November 4, 2023 v0.3.0.234355. So I assume there is a problem with the GMScore v0.3.0.241017.

**Comment by nikhilbadyal** [comment]
What was the requirement for this breaking change ?

**Comment by hey-ir** [comment]
> Why was this breaking change introduced? Any reason ?

Because, Revanced display 「The following content not available on this app」
![image0](https://github.com/YT-Advanced/ReX-patches/assets/165011544/14a80ec1-d312-4c59-90ce-bf0ca6c2e59a)

**Comment by YT-Advanced** [comment]
Clear your patches data and try repatch again
