### ISSUE TITLE
question: Rex, anddea or rufusin patches? 

### ISSUE THREAD

**Issue by weiliang011** [YT-Advanced/ReX-patches#167]
### Application

YouTube

### Question description

What patches its better to use? 

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by tooruu** [comment]
So what's the answer?

**Comment by Destro9000** [comment]
Use the default option

**Comment by tooruu** [comment]
> Use the default option

The "default" option is outdated RVX patches. So the real options are ReX, anddea patches, Rufusin patches.

**Comment by weiliang011** [comment]
> So what's the answer?
Rex:more stable
Anddea:more patches and newer versions of yt
Rufusin:idk
