### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SHREYASHMJ** [YT-Advanced/ReX-patches#169]
YouTube Or YT Music Crash Both On New Micro G

**Comment by yuukiAme** [comment]
which version?

**Comment by SHREYASHMJ** [comment]
> Which version? 
> 
> Name of the gmscore please.

![Screenshot_2024-03-26-21-43-55-68.jpg](https://github.com/YT-Advanced/ReX-patches/assets/91649672/f8cb4c75-0a1f-47da-8818-7b762e46cc9d)

**Comment by yuukiAme** [comment]
Did you get it from [here](https://github.com/YT-Advanced/GmsCore/releases)

Note: that v0.3.1 is gone from that release page. YT-Advanced removed it himself.

You will have to uninstall it through properly with these two commands with ADB from [SDK Platform Tools](https://developer.android.com/tools/releases/platform-tools)

`adb shell pm uninstall -k app.rvx.android.gms`

then `adb uninstall app.rvx.android.gms`

Both messages should **Success** otherwise, you will have conflict package with other gmscore apk. I just saved you around 9 hours of troubleshooting.

**Comment by yuukiAme** [comment]
Now for the explanation on why it crashes when you use YouTube Or YT Music

It's because of the Gmscore and its permission. So right now, the current ReX patch v220.10 won't work with that gmscore. Use the previous RVX and MicroG `com.mgoogle.android.gms` v0.3.0.234914

**Comment by SHREYASHMJ** [comment]
> Now for the explanation on why it crashes when you use YouTube Or YT Music
> 
> It's because of the Gmscore and its permission. So right now, the current ReX patch v220.10 won't work with that gmscore. Use the previous RVX and MicroG `com.mgoogle.android.gms` v0.3.0.234914
> 
> Use [Revanced/Gmscore](https://github.com/revanced/GmsCore/releases) for the latest patch and see if it works.

Bro i used previous com.mgoogle.android.gms`https://github.com/YT-Advanced/ReX-patches/assets/91649672/7aee166f-ad01-4046-aad4-cbf25f18f644

 v0.3.0.234914 and this happened

**Comment by SHREYASHMJ** [comment]
> Now for the explanation on why it crashes when you use YouTube Or YT Music
> 
> It's because of the Gmscore and its permission. So right now, the current ReX patch v220.10 won't work with that gmscore. Use the previous RVX and MicroG `com.mgoogle.android.gms` v0.3.0.234914
> 
> Use [Revanced/Gmscore](https://github.com/revanced/GmsCore/releases) for the latest patch and see if it works.

And i used revanced Gsmcore also this also YT crash

**Comment by yiauta** [comment]
I have found with the new GmsCore v0.3.1.1.240913 YT must be installed for the revanced version to work and the same with YT Music. They will crash when starting otherwise.

**Comment by YT-Advanced** [comment]
1. Make sure that you have downloaded correct GMSCore
Download link: https://github.com/ReVanced/GmsCore/releases
2. Go to settings --> self-check and grant all permission like https://t.me/revanced_extended_chat/309424
3. Install stock YouTube and stock YT Music
