### ISSUE TITLE
feat: Hiding Related Videos for distraction free experience

### ISSUE THREAD

**Issue by matt873** [YT-Advanced/ReX-patches#17]
### Application

Youtube

### Issue

Distraction.

### Patch

Please add an option to hide "Related Videos" under the video being played. This is very useful when someone want to watch videos only from their subscribed channels and Subscriptions tab is set as home screen. This feature is available in LibreTube. Is there possibility of implementing it in official youtube app?

### Motivation

Youtube Unhook experience for saving time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by YT-Advanced** [comment]
Just add `related_video` to Custom Filter is enough

**Comment by matt873** [comment]
I read somewhere that adding this filter can lead to too many requests and eventually account ban. Is there any finer way of implementing this feature like completely disabling related videos from loading instead of filter? And how hard it would be to implement it? Is it possible in theory?
