### ISSUE TITLE
bug: Annoying pop-up

### ISSUE THREAD

**Issue by JakobHunterek** [YT-Advanced/ReX-patches#170]
### Type

Other

### Tools used

Revancify

### Application

YouTube: v19.07.40
ReX Patches: v2.220.10 (Recommended patches plus Material You minus Swipe Controls)

### Bug description

The annoying Please reinstall your stock YouTube from Play Store pops up everytime I launch the app. But other than that, nothing is wrong 
![Screenshot_20240327_115317_ReVanced Extended](https://github.com/YT-Advanced/ReX-patches/assets/139505017/dda3c1e0-f2ca-400c-93fa-697c3c6e755c)

### Solution

IDK

### Device Environment

Android 14 OneUI 6.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Fixed
