### ISSUE TITLE
bug: "YouTube/Full screen/Quick actions" `Hide comment button` & `Hide share button` patches not working properly

### ISSUE THREAD

**Issue by Rairof** [YT-Advanced/ReX-patches#171]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.07.40

### Bug description

`Hide comment button` & `Hide share button` patches doesn't hide comment & share button on Fullscreen respectively.
![IMG_20240328_115713](https://github.com/YT-Advanced/ReX-patches/assets/107706560/44b469aa-e8a2-42a7-8852-c1a7d7013b3c)
![Screenshot_20240328-120430](https://github.com/YT-Advanced/ReX-patches/assets/107706560/c8063671-9931-4c9e-91ad-c7a95535e99e)

### Error logs

```shell
N/A
```

### Solution

Fix related patches.

### Additional context

Using Xiaomi 11T Pro device with custom ROM.

### Device Environment

Android 14, Project Elixir 4.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Can you debug and get the litho component. I think you already know how to do it xD. If not, feel free to inbox me in Telegram

**Comment by anddea** [comment]
Fixed in [v0.150.0-dev.6](https://github.com/anddea/revanced-integrations/releases/tag/v0.150.0-dev.6) and [v0.150.0](https://github.com/anddea/revanced-integrations/releases/tag/v0.150.0).
