### ISSUE TITLE
suggestion: add MDY icons for YT & YTM

### ISSUE THREAD

**Issue by Rairof** [YT-Advanced/ReX-patches#172]
### Application

YouTube

### Suggestion description

the MDY icons for YT & YTM already exists in [here](https://github.com/nyas1/Material-You-app-list?tab=readme-ov-file#-youtube-clients) and official ReVanced already supports it, so I don't see a reason why not to implement it in ReX as well, maybe within `Custom Branding Icon` patch as an option...

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
As I know, Revanced haven't support it

**Comment by Rairof** [comment]
https://github.com/YT-Advanced/ReX-patches/issues/172#issuecomment-2028598627
Seems like it does...

https://github.com/YT-Advanced/ReX-patches/assets/107706560/240124b8-cba7-4b09-b336-005638069b16
