### ISSUE TITLE
bug(YT Music/`Background play`): Background play fails on v6.45.54

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [YT-Advanced/ReX-patches#177]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YT Music v6.45.54

### Bug description

Background play fails on YT Music v6.45.54. It's only failing on v6.45.54.
![Screenshot_20240331_131433_ReVanced Manager](https://github.com/YT-Advanced/ReX-patches/assets/117499019/b936ac1e-17b9-46c5-985a-cf09f8ed47bc)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It was fixed in my repo a week ago. 

And should be fixed in this repo too based on the commits.

**Comment by ILoveOpenSourceApplications** [comment]
v6.46.52 patches successfully but v6.45.54 fails on background play.
Edited my issue to state that it's failing only on that specific version and not any version above 6.45.

**Comment by anddea** [comment]
There's no error for 6.45 in my patches.

**Comment by ILoveOpenSourceApplications** [comment]
I haven't tested with your sources, but I can if needed.

**Comment by ILoveOpenSourceApplications** [comment]
> There's no error for 6.45 in my patches.

Yes, there's no error if the source is changed to your fork. But @YT-Advanced's one fails.

**Comment by YT-Advanced** [comment]
> > There's no error for 6.45 in my patches.
> 
> Yes, there's no error if the source is changed to your fork. But @YT-Advanced's one fails.

I fixed it locally, but too busy to release a new version

**Comment by ILoveOpenSourceApplications** [comment]
> I fixed it locally, but too busy to release a new version

Thanks for confirming. Well somehow it's fine with 6.46.52 so I updated to that one instead, so no rush.

**Comment by ILoveOpenSourceApplications** [comment]
`Background play` once again fails on the latest YT Music v6.49.53.
