### ISSUE TITLE
3 Questions about Revanced Extension App

### ISSUE THREAD

**Issue by geedogz** [YT-Advanced/ReX-patches#179]
### Application

YouTube

### Question description

Hi.. 2 things:

1) I'm confused. Is this the github team for the rex app itself or for the patches? I'm new to revanced and want to know the difference between the two.

2) Can you update the app so that one can increase the font size of the description part of the yt video in rex?

3) Where on this github can I download just the rex app itself?

.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Sam101011** [comment]
1. ReX is a fork of revanced, maintained(in the most part) by a single developer
2. You can increase the font size from your phone's settings
3. Please read [the documentaion](https://github.com/YT-Advanced/revanced-documentation).
