### ISSUE TITLE
bug: Font Size is Too Small in Description Part of YT Videos

### ISSUE THREAD

**Issue by geedogz** [YT-Advanced/ReX-patches#181]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Rex latest version

### Bug description

I have non-root rex, the app. The font size in the Description part of the videos on yt is a bit small. I request that you make it bigger in the next update to non-root, rex app only, not patches. Thanks. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
You can change the font size in your devices settings
