### ISSUE TITLE
[Feature request] Filter YouTube feed and search result.

### ISSUE THREAD

**Issue by smed79** [YT-Advanced/ReX-patches#183]
#### Application

YouTube

#### Feature description

Add ability to filter/block/hide **videos** based on their tags/title/keyword or **entire channels** based on channel name, handle or channel ID.

#### Motivation

I want to tell Youtube to **shut up**.

This has been happening for a long time but I decided to post this feature request today when the YouTube algorithm decided to fill my search result with ridiculous video with the title "_how to enlarge your butt?_" as a result of my research relating to "_raid parity_".

Youtube is strictly educational for me and if i want entertainment i know what to see or who to follow. 

I've been giving tons of thumbs-downs and do not recommend channel, but if I scroll down, for some reason I keep getting pissed off by clickbait videos and unrelated recommendation to the content that I watch or search for. Some videos are quite hurtful.

#### Similar topics

- [startpage.com/rvd/search?query=unrelated%20irrelevant%20youtube%20search%20results](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.startpage.com/rvd/search?query=unrelated%20irrelevant%20youtube%20search%20results)

#### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
`Keyword filter` was implemented weeks ago in my repo, it hides content by your keywords not only in home feed, but also in search feed, subscriptions and comments. 

https://github.com/anddea/revanced-patches/releases/tag/v2.223.0

**Comment by smed79** [comment]
Thank you for your response and the work you do for the YouTube community 🙏

I patched `YouTube 19.11.38` with @anddea revanced patch `2.223.0 (2024-04-01)` mentioned above and the result is that the patch works relatively for me.

- Hide entire channels by `channel name`.

add `Linus Tech Tips` 
search for `cpu`.

✓ video from the mentioned channel are hidden 👍

- Hide entire channels by [handle](https://support.google.com/youtube/answer/11585688).

add
```
@LinusTechTips
LinusTechTips
linustechtips
```

search for `cpu`

✗ video from the mentioned channel are not hidden 👎

- Filter video by keyword in Trending feed.

add the keyword `Rugby`
explore Trending feed

✗  video in feed from `NLR` channel are not hidden 👎

- Filter video by `keyword in search`.

add `wwe`
do a search for `wwe`

✗ shows a [strange strip layout](https://i.imgur.com/fPLbuSj.jpeg) with thumbnail and if clicked, shows an empty box.


I am wondering if i missed something in my setup? If it is the case you help is welcome.

**Comment by anddea** [comment]
The `Keyword filter' supports everything you see in the feed. So, if the channel name consists of individual (seperated) words, then this is the right way, you can't hide it with a handle/descriptor or whatever, but you can hide it by the channel name. 

It hides only the video content for feeds and only the content of comments for comments section, it does not hide the expandable element under the video or comment replies. To hide expandable elements under videos you can enable Extended > General > Hide expandable chips under video, but then you will have an empty space. There is no better solution to hide everything altogether for now.

**Comment by smed79** [comment]
@anddea I played around more with the settings and added more keywords, then did more testing and the result is as I expected. In most cases, unwanted search results are filtered out.

I hope other forks implement (and improve) similar functionality so that all users benefit.

Thanks again for taking the time to respond and help me here.

@YT-Advanced I will leave you the task take in consideration the implementation of the keywords filtering in YT-Advanced patches or reject and close this issue.

@inotia00 FYI.

**Comment by smed79** [comment]
@anddea The feature `Keyword filter` does not work property with the last revanced patches 2.224.0 and youtube 19.16.38.

Settings: https://i.ibb.co/Yp80Y99/kwf.jpg

Please check if it is a bug.

**Comment by anddea** [comment]
> The feature `Keyword filter` does not work property with the last revanced patches 2.224.0 and youtube 19.16.38.

Could you elaborate? What specifically doesn't work? Examples? I think it would be better if you opened an issue in my repo so we don't spam here.

**Comment by smed79** [comment]
Ok, i will open a bug issue later.

Sorry for the noise here. Closing ...
