### ISSUE TITLE
suggestion: make a toggle for `Hide fullscreen button` patch

### ISSUE THREAD

**Issue by STEK1337** [YT-Advanced/ReX-patches#184]
### Application

YouTube

### Suggestion description

Name of this patch is `Hide fullscreen button`, description says "Force to hide fullscreen button" 
Clearly it wasn't ment to force hide it, so it will be better to make a toggle inside revanced extended settings

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Since this patch was made by anddea & later added to ReX-patches, you can ask about it here:
 https://github.com/anddea/revanced-patches
