### ISSUE TITLE
bug(YT Music/`Hide Ads`): Fullscreen YT premium pop-up showing in YT Music

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [YT-Advanced/ReX-patches#185]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT Music v6.46.52

### Bug description

The YouTube premium promotional fullscreen ads are showing up in YT Music app.
![Screenshot_20240407_194929_YouTube Music](https://github.com/YT-Advanced/ReX-patches/assets/117499019/ca12d391-84e3-453a-aae0-b585ef6566d8)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
Hi @YT-Advanced, I'm also getting the premium renewal banner as well. Maybe the ads patch require some tweaking for the newer versions of YT music.
![Screenshot_20240415_004025_YouTube Music](https://github.com/YT-Advanced/ReX-patches/assets/117499019/bda5d1fd-c6cc-4f40-b812-44ad595d741c)

**Comment by YT-Advanced** [comment]
It got removed long time ago in YTM

**Comment by ILoveOpenSourceApplications** [comment]
Wasn't it the interstitial ads option which was removed?
Also, in ReVanced YTM, there's no such ads at the moment. So why don't we consider copying their filter?
