### ISSUE TITLE
bug (YouTube/`Hide shorts components`): `Hide info panels` also hides sound metadata label and video link label

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [YT-Advanced/ReX-patches#188]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.11.43

### Bug description

Toggling on hide info panels also hides sound metadata label and video link label in the case of Shorts.
| Before  | After |
| ------------- | ------------- |
| ![Screenshot_20240417_134909_YouTube](https://github.com/YT-Advanced/ReX-patches/assets/117499019/e122f139-bfed-4370-95d8-b9f11b8286d0) | ![Screenshot_20240417_13 4906_YouTube](https://github.com/YT-Advanced/ReX-patches/assets/117499019/73326436-c21a-40b3-b1cf-65c773819aa9) |
| ![Screenshot_20240417_134753_YouTube](https://github.com/YT-Advanced/ReX-patches/assets/117499019/d6a531d9-46e3-4bbe-bd59-5dd5c58682e9) | ![Screenshot_20240417_134839_YouTube](https://github.com/YT-Advanced/ReX-patches/assets/117499019/2ffcb43e-2290-49d7-b670-cd873556a2df) |

### Solution

ReVanced has no such problem, as of writing this issue and simply copying their code for the `Hide info panels` option should do the trick.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
Also @rufusin, thanks to your description I noticed this issue, but I also noticed the same for normal videos hide info panel as well. I am confused on what sound metadata label and video link label is for normal videos? If it's not too much can you explain what it's hiding when toggled on?

**Comment by ILoveOpenSourceApplications** [comment]
@anddea, is the code for hide info panels same as official ReVanced's one? I didn't notice this bug there and that's why I am asking.

**Comment by anddea** [comment]
Hide info panel in official ReVanced is a different thing. What does it hide there exactly? 

These are also not my patches, because I have disclaimer that `hide info panels` covers two of the settings, but they all available just because maybe someone needs more flexible settings.

**Comment by ILoveOpenSourceApplications** [comment]
WHO's (World Health Organization) official YouTube channel has info panel in most of their shorts. This one has all 3 components: https://youtube.com/shorts/08XopmNwEcA

Info panel (The one at the very bottom):
![Screenshot_20240427_110529_YouTube](https://github.com/YT-Advanced/ReX-patches/assets/117499019/ad0939c4-e902-4563-8765-38de6685c0d9)

**Comment by ILoveOpenSourceApplications** [comment]
> Also @rufusin, thanks to your description I noticed this issue, but I also noticed the same for normal videos hide info panel as well. I am confused on what sound metadata label and video link label is for normal videos? If it's not too much can you explain what it's hiding when toggled on?

@anddea, what's this in normal video?
![Screenshot_20240427_114712_YouTube](https://github.com/YT-Advanced/ReX-patches/assets/117499019/1b141113-7e18-4633-ba62-617411782765)

**Comment by ILoveOpenSourceApplications** [comment]
The litho components for each I found are:
1) Info panels: `shorts_info_panel_overview.eml`
2) Sound metadata label: `reel_sound_metadata.eml`
3) Full video link label: `reel_multi_format_link.eml`

```kotlin
04-27 22:35:59.474 22951 22951 D revanced: LithoFilterPatch: Searching ID: shorts_info_panel_overview.eml|b53528b7b6e37626 Path: shorts_info_panel_overview.eml|b53528b7b6e37626|ContainerType| BufferStrings: yt_outline_chevron_right_black_24Γ¥ÖFrom an international health authorityΓ¥Ösans-serif-mediumΓ¥Öyt_outline_shield_plus_black_24Γ¥ÖFrom an international health authorityΓ¥Ö*engagement-panel-shorts-info-panel-detailsΓ¥Ö1714237559661932399Γ¥Öshorts_info_panel_overview.eml|b53528b7b6e37626Γ¥Ö
04-27 22:35:59.443 22951 22951 D revanced: LithoFilterPatch: Searching ID: null Path: reel_metapanel.eml|ec3bfd7c238b45c7|ContainerType|reel_sound_metadata.eml|bb9ea48760404cc8|ContainerType| BufferStrings: FEsfv_audio_pivotΓ¥Öd8gVDCjYSJwoLMDhYb3BtTndFY0ESCzA4WG9wbU53RWNBGgswOFhvcG1Od0VjQRoLMDhYb3BtTndFY0Eo0-Lhmp7Cv7aTAQ%3D%3DΓ¥ÖOriginal SoundΓ¥Öyt_outline_music_black_18Γ¥ÖOriginal SoundΓ¥ÖFEsfv_audio_pivotΓ¥Öd8gVDCjYSJwoLMDhYb3BtTndFY0ESCzA4WG9wbU53RWNBGgswOFhvcG1Od0VjQRoLMDhYb3BtTndFY0Eo0-Lhmp7Cv7aTAQ%3D%3DΓ¥Ö
04-27 22:35:59.423 22951 22951 D revanced: LithoFilterPatch: Searching ID: reel_metapanel.eml|ec3bfd7c238b45c7 Path: reel_metapanel.eml|ec3bfd7c238b45c7|ContainerType| BufferStrings: reel_sound_metadata.eml|bb9ea48760404cc8Γ¥Öshorts_video_title_item.eml|f596473294ac2024Γ¥Öreel_multi_format_link.eml|1d9dd71bcd46b070Γ¥ÖKey_ReelChannelBarInnerWithControllerΓ¥Öreel_channel_bar.eml|9869ec9b4901eecaΓ¥Ö1714237559661932402Γ¥Öreel_metapanel.eml|ec3bfd7c238b45c7Γ¥Ö
```

**Comment by ILoveOpenSourceApplications** [comment]
Also `Hide video link label` should be renamed to `Hide full video link label` as it's hiding the link to the full video version of the Shorts.

**Comment by ILoveOpenSourceApplications** [comment]
@anddea, are these the same litho components used?

**Comment by anddea** [comment]
Not sure what do you mean here. Info panels for Shorts option hides both of those elements. You either hide one of them if you wish or hide both of them by switching one toggle instead of 2.

**Comment by ILoveOpenSourceApplications** [comment]
I'm talking about the warning in the description, `It will also hide sound metadata label and video link label`. This behavior isn't present in ReVanced. I have even [commented](https://github.com/YT-Advanced/ReX-patches/issues/188#issuecomment-2080374675) the link to a Shorts having all 3 components.

**Comment by anddea** [comment]
Original ReVanced doesn't have it because they hide different element for info panel. RVX always had this option before, that hides everything with one toggle switch, lately ReVanced team added new options to hide more elements and we just added them as well if someone wants to have flexible settings, i.e. hide just one portion of the whole element (or elements) that is hidden by "Hide info panel". You want it to match and remove one switch for all and instead just hide info panel (the one which is not present for all videos) like ReVanced?

**Comment by ILoveOpenSourceApplications** [comment]
> You want it to match and remove one switch for all and instead just hide info panel (the one which is not present for all videos) like ReVanced?

Yes. While it's true that info panels isn't present in all Shorts, it is something no one preferably wants to see. Now on the other case, some may use the full video link panel as watching the shorts may peak an interest for the user to watch the full video. Given that we have separate toggles to hide one and the other, why not make hide info panels to only hide it?

**Comment by anddea** [comment]
I can replace Hide info panels, or I can do the same thing what I did with Hide shorts for different tabs (keep Master setting that disables all of them) but we have to come up with the naming and default values. What do you think is better?

You can open a Pull Request with your changes if you want.

**Comment by ILoveOpenSourceApplications** [comment]
> I can replace Hide info panels

I think that would be the easiest. With that change the users are given the choice to have what they want to see and what not.
