### ISSUE TITLE
bug: swipe up full screen on vertical turns in to horizontal.

### ISSUE THREAD

**Issue by limonetas** [YT-Advanced/ReX-patches#19]
### Type

Other

### Bug description

the recent patch produces this error, and I have patched it with revancify armv8.

### Steps to reproduce

just happens idk.

### Relevant log output

```shell
I don't know what it is, if you could explain me how to see the logs on youtube, I'd appreciate it! XD
```

### Screenshots or videos

https://github.com/YT-Advanced/ReX-patches/assets/47794002/c9775292-3fac-460d-bf4b-1f8a17500122

### Solution

good luck in solving the problem! :D

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by YT-Advanced** [comment]
Can you reproduce it in original Youtube

**Comment by limonetas** [comment]
> Can you reproduce it in original Youtube

It is a question? I don't have the original YouTube, but yes have it's from last patch of inotia and it doesn't have that problem.

**Comment by YT-Advanced** [comment]
I think it is a bug from Youtube because my patch (and also inotia patch) didn't changed anything related to the swipe

**Comment by andylee516** [comment]
i tried 18.34.37 with patch 2.190.0 but it is same. we cant scroll up to see fullscreen normally.

**Comment by YT-Advanced** [comment]
Seem like it is Youtube bug itself, you can see in this message:
https://t.me/revanced_extended_chat/253109
