### ISSUE TITLE
bug: options stretch to full screen not working

### ISSUE THREAD

**Issue by electrifying** [YT-Advanced/ReX-patches#21]
### Type

Other

### Bug description

when you enable the option in the settings-general-stretch to full screen section, the function no longer works correctly.black bars remain on the sides and for the option to work, the video has to be stretched manually, this only works until the application is restarted, the problem appeared quite recently, apparently YouTube changed something on the backend side. 

### Steps to reproduce

1.open youtube
2.tap to you avatar 
3.open settings
4.open general
5.activate the option to stretch to full screen
6.open any video
7.switch to full screen video view

### Relevant log output

```shell
sorry i don't have it installed adb
```

### Screenshots or videos

https://github.com/YT-Advanced/ReX-patches/assets/37656577/93838c4f-04e5-479b-9daa-009f5be04927

as you can see at 0:28, I manually stretched the video for borderless viewing, then turned on the video with the game re 4 and the setting was saved, but after unloading the application, the video again in full screen mode starts playing with stripes

### Solution

no solution, at least I couldn't find it

### Additional context

yt-Advanced REX v 18.32.39 root  installed as a module magisk
oneplus 9r android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by YT-Advanced** [comment]
It is Youtube bug itself

**Comment by electrifying** [comment]
> It is Youtube bug itself
There is no this bug in the original YouTube

**Comment by YT-Advanced** [comment]
Hmm, not sure why but I found this message:
https://t.me/revanced_extended_chat/253109
