### ISSUE TITLE
feat: custom player opacity patch

### ISSUE THREAD

**Issue by MondayNitro** [YT-Advanced/ReX-patches#23]
### Application

please add this feature released in 2.188.0 release of revanced patches
![Web capture_6-9-2023_94620_github com](https://github.com/YT-Advanced/ReX-patches/assets/87489540/c2d7a5c5-71bc-4c6e-8dde-6a6d0bfeed62)

### Issue

.

### Patch

.

### Motivation

good feature i think

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by YT-Advanced** [comment]
Why you need it ?

**Comment by YT-Advanced** [comment]
@itsmartashub We already have hide player overlay patch

**Comment by MondayNitro** [comment]
> @itsmartashub We already have hide player overlay patch

bro you should replace hide overlay with custom overlay since the patch is more flexible. put 0% to hide the overlay. please consider adding the patch

**Comment by YT-Advanced** [comment]
> > @itsmartashub We already have hide player overlay patch
> 
> bro you should replace hide overlay with custom overlay since the patch is more flexible. put 0% to hide the overlay. please consider adding the patch

But why ?
