### ISSUE TITLE
feat: Hide "Privacy Policy" & "Terms of Service" in Account Menu page.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#24]
### Application

YouTube

### Issue

Kindly add support for hiding "Privacy Policy" & "Terms of Service" from Account Menu page.

### Patch

This is what I'm talking about.
![IMG_20230906_105155](https://github.com/YT-Advanced/ReX-patches/assets/91815107/48e347aa-6284-49fe-8055-eff7ca810717)

### Motivation

It provides a clean look.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by MrNorthernLights** [comment]
This is server side addition, therefore it can not be hidden.
