### ISSUE TITLE
bug: Some problems in Flyout Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#28]
### Type

Cosmetic

### Bug description

Please add an option to hide these from Flyout Menu:
1. Lock Screen
2. Additional Settings.
3. Report (option is there, but not working).
![h](https://github.com/YT-Advanced/ReX-patches/assets/91815107/0782a813-5c7d-4030-a8cf-26b6ab2e21f4)
![j](https://github.com/YT-Advanced/ReX-patches/assets/91815107/2c1dbab4-785b-4852-83d1-ec8cd6211378)

### Steps to reproduce

Very simple to reproduce.

### Relevant log output

```shell
No logs.
```

### Screenshots or videos

Given above.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Mohammed1520** [comment]
Me too having this issue

**Comment by Adity1243** [comment]
Must be probably bcus of A/B testing try to patch again and reinstall that issue must be fixed.

**Comment by Mohammed1520** [comment]
> Must be probably bcus of A/B testing try to patch again and reinstall that issue must be fixed.

I have opened an issue regarding this problem in inotia repo and he told me to patch with the least supported version. I have done this but the problem still exists
So let's wait for fix in the upcoming updates

**Comment by ran-some** [comment]
Lock screen and stable volume options not shown even if i disabled these options in inotia00's new patches v2.190.15.

**Comment by Adity1243** [comment]
Bro its A/B testing this options come when you first installed the app and launched it but when you launch app second or third time those A/B testing features will vanish and you will get old layout

> Lock screen and stable volume options not shown even if i disabled these options in inotia00's new patches v2.190.15.

**Comment by ran-some** [comment]
In new inotia00's patches v2.190.18 not solve this issue, lock screen and stable volume layout still not visible if i disable these options..

**Comment by Adity1243** [comment]
Bro its A/B testing they option wobt stay permanently on your phone they just come for some time and vanish.
