### ISSUE TITLE
feat: Ability to hide useless text in Captions Selector Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#29]
### Application

YouTube.

### Issue

This text in the Captions Selector Menu isn't much useful. So, please add an option to hide it.
Thanks!
![IMG_20230908_144531](https://github.com/YT-Advanced/ReX-patches/assets/91815107/f0abe19c-7d36-4b92-a08f-b00ba271cd43)

### Patch

Described above.

### Motivation

Hiding irrelevant & useless stuff is the speciality of ReVanced Extended, so that's the motivation, in my opinion.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by YT-Advanced** [comment]
Added in lastest version
