### ISSUE TITLE
bug: ReVanced Extended Settings

### ISSUE THREAD

**Issue by Zaynee77** [YT-Advanced/ReX-patches#31]
### Type

Other

### Bug description

Unable to click on "Bottom Player" settings.

- Youtube Version: `18.35.35`
- ReX-patches Version: `2.190.1`

### Steps to reproduce

1. Go to ReVanced Extended
2. Click on "Bottom Player"

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://github.com/YT-Advanced/ReX-patches/assets/125785889/a2342238-1a2d-4261-9bc7-d68e72f7d256

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Rairof** [comment]
Please repatch and reinstall said patched ReVanced since it seems to work for me and I'm on latest patch as well. It might be caused due to some broken previously kept patch options/menus that wasn't removed properly while updating to latest version.

**Comment by YT-Advanced** [comment]
I can click it normally, pls repatch and reinstall again
