### ISSUE TITLE
bug: Unable to enter revancify after patch latest version update

### ISSUE THREAD

**Issue by sssh7710** [YT-Advanced/ReX-patches#32]
### Type

Other

### Bug description

I received the latest patch, entered the patch menu, bounced, and entered again, so the script won't open

### Steps to reproduce

Receive the latest patches with revancify and enter the Patch Selection menu

### Relevant log output

```shell
.
```

### Screenshots or videos

https://github.com/YT-Advanced/ReX-patches/assets/98168192/cc1756bf-b2f2-4a62-b71e-42dc34114f38

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Mohammed1520** [comment]
It is solved now 
Refer to https://t.me/revancifychat/42359
