### ISSUE TITLE
bug: Hiding both footer text not working in v2.190.1 ReX patches.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#33]
### Type

Cosmetic

### Bug description

The newly added "Hide Captions Menu Footer Text" feature isn't working.

Earlier, "Hide Quality Menu Footer Text" was working fine, but now it is also not working.

### Steps to reproduce

Just enable the hiding option of both.

### Relevant log output

```shell
No logs.
```

### Screenshots or videos

![Screenshot_2023-09-10-08-02-22-57_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/YT-Advanced/ReX-patches/assets/91815107/d9d3e63a-23d4-47c2-a643-6d646afc1c0c)
![Screenshot_2023-09-10-08-02-43-41_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/YT-Advanced/ReX-patches/assets/91815107/9c946f7b-dfc5-45ae-9c7d-d7fb87a2834b)
![Screenshot_2023-09-10-08-03-04-14_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/YT-Advanced/ReX-patches/assets/91815107/71064693-3ede-4bd5-8dab-bfd787570ce3)

### Solution

Solution is fixing them, whenever Alireza gets free time.

### Additional context

Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by YT-Advanced** [comment]
You spoofed your app to old version ?

**Comment by Aryan-Chauhan** [comment]
> You spoofed your app to old version ?

I spoofed to 18.23.35, now it is working fine.
