### ISSUE TITLE
Hide playback history 

### ISSUE THREAD

**Issue by ronin08** [YT-Advanced/ReX-patches#34]
### Application

YouTube 

### Issue

Remove the red progress bar from watched/partially watched video.

![IMG_20230913_140228](https://github.com/YT-Advanced/ReX-patches/assets/75478274/7dea1452-a6ec-416d-9f4f-74279a60013d)

### Patch

Playback history should not be remembered by youtube. 

Note: Disabling history from default youtube settings will turn off the home feed completely. That's why this patch is requested.

### Motivation

It's annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by StradivariusKane** [comment]
ReX settings > Seekbar > Hide seekbar in video thumbnails.

**Comment by Adity1243** [comment]
Its done lol.
