### ISSUE TITLE
bug: REX 18.36.39  I'm using this version, and it appears even if I turn on hiding the information card.

### ISSUE THREAD

**Issue by root-kernelhacker** [YT-Advanced/ReX-patches#37]
### Type

Error while patching

### Bug description

REX 18.36.39

I'm using this version, and it appears even if I turn on hiding the information card.

### Steps to reproduce

REX 18.36.39

I'm using this version, and it appears even if I turn on hiding the information card.

### Relevant log output

```shell
REX 18.36.39

I'm using this version, and it appears even if I turn on hiding the information card.
```

### Screenshots or videos

![Screenshot_20230922_142658_YouTube](https://github.com/YT-Advanced/ReX-patches/assets/132817163/7bf51377-c2b4-44c4-a6d3-bd78e2c2b870)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by s7san007** [comment]
Unsupported version. Spoof to 18.20.39 or type in filter `info_card`

**Comment by Adity1243** [comment]
Patch again with latest rex patch after patch got fixed announcement given.
