### ISSUE TITLE
bug: testpatches build error

### ISSUE THREAD

**Issue by root-kernelhacker** [YT-Advanced/ReX-patches#39]
### Type

Error while patching

### Bug description

If you specify testpatches in the manager app, the patch appears as test patch 2.192.0, but an error occurs while building.  If you build with ReX-patches specified, it builds without error.  Is there another way to build with testpatches using the manager app?

### Steps to reproduce

manager app used.

### Relevant log output

```shell
build error.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by YT-Advanced** [comment]
Don't use it
