### ISSUE TITLE
feat: Update ReX to 2.220.1

### ISSUE THREAD

**Issue by RoonMoonlight** [YT-Advanced/ReX-patches#44]
### Application

ReX 2.192.2

### Issue

The patch is outdated, RVX development has stopped once again. This patch needs to be updated to latest one.

### Patch

Update all patches to 2.220.1

### Motivation

RVX development has stopped and we need your fork of RVX as alternative.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Xisrr1** [comment]
Please continue this🙏
