### ISSUE TITLE
Power Save Mode

### ISSUE THREAD

**Issue by rufusin** [YT-Advanced/ReX-patches#46]
### Feature description

Hello.  Tell me how to correct PowerSaveModeFingerprint.kt to apply it not only to version 19.04.xx, but 19.05.xx.  Thank you!

### Motivation

New version

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by YT-Advanced** [comment]
What do you mean ???

**Comment by rufusin** [comment]
Correct this patch for version 19.05.xx

**Comment by YT-Advanced** [comment]
Hmm but now the latest version of ReX is still v19.04

**Comment by rufusin** [comment]
It's time to move on
