### ISSUE TITLE
Cant import settings from file

### ISSUE THREAD

**Issue by speedlorenzo12** [YT-Advanced/ReX-patches#49]
### Bug description

when I try to import the settings from the file it says impossible to import settings, the first time I went to Rex I had this problem, in fact I used the text instead of the file and in the end I exported to overwrite it but this problem continues to exist

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by YT-Advanced** [comment]
Hmm I have no idea

**Comment by speedlorenzo12** [comment]
I found the problem, it's a writing error in the backup code, I fixed it

**Comment by speedlorenzo12** [comment]
I found the problem, it's a writing error in the backup code, I fixed it
