### ISSUE TITLE
bug: "Certificate Spoof" android auto does not work online

### ISSUE THREAD

**Issue by Radical4ever** [YT-Advanced/ReX-patches#50]
### Bug description

So, using the certificate spoof patch makes the app work on android auto but only on local songs, if i try to look for my liked songs im unable to, but using the app on the phone to look up for them, they're recognized on the app and i can see the song queue even, i tried woth only that patch enabled and microg but still no working.

Steps:
-connect device to android auto
-select YT Music
-cant see the full ui only library and device files

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by YT-Advanced** [comment]
Hmm now I don't have Android Auto devices to test, so it is hard to create a fix for this feature. However, I will remove this patch because it no longer worked.

Or you can let me know the last version that Certiface Spoof worked

**Comment by Radical4ever** [comment]
I'm unable to tell you when this started bc, i got the car in oct 2023 and since then i had the issue, some other issues i tried looking for dated from april of 2023, so its hard for me to know that.
On the other matter i found this documentation of how to try [Android Auto apps on Pc](https://developer.android.com/training/cars/testing?hl=es-419#test-auto) i hope it helps, it would be fire if this issue is fixed up
