### ISSUE TITLE
bug: "Hide channel avatar section" not working

### ISSUE THREAD

**Issue by STEK1337** [YT-Advanced/ReX-patches#54]
### Bug description

Channel avatar section of the subscriptions feed is not working

### Additional context

_Galaxy A53 5G Stock ROM
Android 14
Patches version: 2.220.4
Integrations version: 0.143.0
YouTube v19.04.37_

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by YT-Advanced** [comment]
Hi, include the `Debugging patch` then repatch. After that, contact me in Telegram. Thanks

**Comment by STEK1337** [comment]
Sent you a DM on telegram
