### ISSUE TITLE
bug (YouTube/Hide Suggested Video Overlay): Suggested video thumbnail in minimized player

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [YT-Advanced/ReX-patches#63]
### Bug description

While the user finishes watching a video, the preview when minimized shows a different video thumbnail as well as the autoplay button rather than the videos last frame and replay button.

https://github.com/YT-Advanced/ReX-patches/assets/117499019/bdc863f3-8baa-4f88-8288-961908a1b77d

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by YT-Advanced** [comment]
This is YouTube "feature" itself. You can test it in stock YouTube

**Comment by ILoveOpenSourceApplications** [comment]
Yes, it's a feature which can be hidden using `hide suggested video overlay`. This is a bug related to that patch. 
In stock YouTube:

https://github.com/YT-Advanced/ReX-patches/assets/117499019/7f0c6d1b-4f9b-4465-a719-64c64ff4b5fd

**Comment by ILoveOpenSourceApplications** [comment]
The suggested video overlay is hidden if the user stays on portrait or full screen mode. But if minimized it bugs and shows the thumbnail of the suggested video with the autoplay button which disappears after previewing and minimizing once again.

**Comment by ILoveOpenSourceApplications** [comment]
@YT-Advanced, I hope you understand that this is a genuine bug report and re-open the issue. Thanks!
