### ISSUE TITLE
suggestion(YouTube Music): rename `Hide new playlist button` patch to `Hide new playlist and shuffle all buttons`

### ISSUE THREAD

**Issue by girshcatt** [YT-Advanced/ReX-patches#64]
### Application

YouTube Music

### Suggestion description

Rename `Hide new playlist button` patch to `Hide new playlist and shuffle all buttons`
Because it hides also `Shuffle all` button in `Device files`

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Hmm I think it is better to add the `Shuffle all` as unexpected behavior

**Comment by YT-Advanced** [comment]
Also can you do a PRs, thanks
