### ISSUE TITLE
bug(YouTube/Quick actions components): `Hide comment button` setting does not work

### ISSUE THREAD

**Issue by girshcatt** [YT-Advanced/ReX-patches#66]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.29.38

### Bug description

`Hide comment button` setting does not work
![IMG_20240209_103654_580](https://github.com/YT-Advanced/ReX-patches/assets/110785596/308907e1-0040-4e83-8d78-a843cc2aac64)
![IMG_20240209_103654_861](https://github.com/YT-Advanced/ReX-patches/assets/110785596/60e81fa9-de3a-41c9-ab45-1c175dfc81e5)

### Error logs

```shell
:/
```

### Device Environment

Android 13, MIUI 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
https://github.com/YT-Advanced/RVX_BUG_CENTER/issues/14
