### ISSUE TITLE
feat(YouTube): Hook download button for Flyout Menu

### ISSUE THREAD

**Issue by YT-Advanced** [YT-Advanced/ReX-patches#70]
### Application

YouTube

### Feature description

Currently, the hook download button patch are being handled if we click `Download this video` in the flyout menu. However, the downloaded video is incorrect because the limitation of current patching method.

### Motivation

- It is a cool feature
- I'm the owner, I can do anything I want

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
Can this also be implemented in ytm?
