### ISSUE TITLE
bug: Autoplay disabled does not work -> stil playing videos

### ISSUE THREAD

**Issue by AlpenMeister** [YT-Advanced/ReX-patches#71]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Youtube 19.04.37 all patches included

### Bug description

When disabling auto-play on videos when a video is finished it stills goes to another video.

### Solution

Fix it :)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Settings --> Player --> Scroll down and find "Disable Suggested Video Overlay", below this option is the autoplay settings
