### ISSUE TITLE
suggestion: Rework on `Enable colour match player` patch for ytm versions above 6.34.51

### ISSUE THREAD

**Issue by Rairof** [YT-Advanced/ReX-patches#72]
### Application

YouTube Music

### Suggestion description

I know this patch is deprecated since YouTube music version 6.34.51 but the current minimised player just looks really dull/ugly with only amoled dark mode. Maybe it's possible for you to somehow make this patch work again through different methods or means.. I would really love to see this patch working again in later versions as it gives the player more vibrance and colour and I and others really love it. ❤️
![Screenshot_20240211-045343](https://github.com/YT-Advanced/ReX-patches/assets/107706560/244b57ec-d613-47d7-beae-722fd215dbc5)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
I also requested this as Fullscreen colours works, it's just the mini player that's broken

**Comment by Rairof** [comment]
I also requested this as Fullscreen colours works fine, it's just the mini player that's broken. So I thought with just a bit more work and fixing might bring that patch back to later versions as well..

**Comment by broli95** [comment]
I love this feature too, main reason why I use extended instead of regular revanced, hope it's possible to add it back

**Comment by Aryan-Chauhan** [comment]
This is a reasonable feature request.

I'm also missing this patch.

**Comment by ILoveOpenSourceApplications** [comment]
Hi guys, I had actually opened a feature request in ReVanced Patches repository for the same feature but it was rejected as a niche feature and wasn't required by the masses. But somehow I convinced [oSumAtrIX](https://github.com/oSumAtrIX) to agree if a large number of people wanted this feature he may consider it. I'm linking my request below and if possible please provide a thumbs up so that it'll be considered as a request and be implemented, who knows when, but still someday we can have it in ReVanced as well.
Link: https://github.com/ReVanced/revanced-patches/issues/606

Thanks to those who took their time to show support.

**Comment by broli95** [comment]
> Hi guys, I had actually opened a feature request in ReVanced Patches repository for the same feature but it was rejected as a niche feature and wasn't required by the masses. But somehow I convinced [oSumAtrIX](https://github.com/oSumAtrIX) to agree if a large number of people wanted this feature he may consider it. I'm linking my request below and if possible please provide a thumbs up so that it'll be considered as a request and be implemented, who knows when, but still someday we can have it in ReVanced as well.
> Link: https://github.com/ReVanced/revanced-patches/issues/606
> 
> Thanks to those who took their time to show support.

I left a thumbs up on your issue page, hope more do the same, I love this feature

**Comment by ILoveOpenSourceApplications** [comment]
> I left a thumbs up on your issue page, hope more do the same, I love this feature

I'm also hoping for the same.
