### ISSUE TITLE
feat: `crossfade` patch

### ISSUE THREAD

**Issue by Rairof** [YT-Advanced/ReX-patches#73]
### Application

YouTube Music

### Feature description

Crossfades between 2 songs at the end to provide a seamless continuous music experience.

![Screenshot_20240211-053237](https://github.com/YT-Advanced/ReX-patches/assets/107706560/e9d2d557-3772-4a12-8faf-9f77835154fe)

### Motivation

Would be pretty nice to have it as it crossfades the next song's starting with current song's ending based on the seconds we choose. Basically same as Spotify crossfade option.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
This feature requires preloading the next video, which is too much for me
