### ISSUE TITLE
bug: YouTube like button glow

### ISSUE THREAD

**Issue by blacktornadog7** [YT-Advanced/ReX-patches#76]
### Type

Cosmetic

### Tools used

CLI

### Application

YouTube v19.04.37

### Bug description

when someone says "hit that button" or something similar the like button glows but its size doesn't match because of Return YouTube Dislike (RYD)

### How it looks on mobile:
https://github.com/YT-Advanced/ReX-patches/assets/74029985/c5a90b88-63b0-457f-b759-aa103f390d00

### How it looks on pc:
https://github.com/YT-Advanced/ReX-patches/assets/74029985/4882ad6c-fbea-4455-95b1-b0d8dbac6282

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1738
