### ISSUE TITLE
bug: YouTube Music stuck in English only

### ISSUE THREAD

**Issue by blacktornadog7** [YT-Advanced/ReX-patches#77]
### Type

Cosmetic

### Tools used

CLI

### Application

YouTube Music v6.37.50

### Bug description

 YouTube Music is stuck in English only and can't switch it to any other language even when manually changing it from app settings.
Tried it on another device: language switching works fine but some settings are still English only

| how it look on my phone:    | how it look on another phone: | how it looks on stock app (not patched):
| ---------------------------------- | ----------------------------------- |----------------------------------- | 
| ![Screenshot_20240211_121620_ReVanced Extended Music](https://github.com/YT-Advanced/ReX-patches/assets/74029985/4298390e-9b9c-4cbf-8471-d4ba807155e5) | ![Screenshot_20240211_122004_ReVanced Extended Music](https://github.com/YT-Advanced/ReX-patches/assets/74029985/5505e2bf-f26c-4f13-8b2b-74bf0539f2b0) | ![Screenshot_20240211_131453_YouTube Music](https://github.com/YT-Advanced/ReX-patches/assets/74029985/3a936005-2b74-4200-bf78-d3a0304453b1) | 
| ![Screenshot_20240211_121637_ReVanced Extended Music](https://github.com/YT-Advanced/ReX-patches/assets/74029985/8aa9bed8-d66e-4d5b-bc2c-7ad0c57a2034) | ![Screenshot_20240211_122014_ReVanced Extended Music](https://github.com/YT-Advanced/ReX-patches/assets/74029985/887dbc07-d752-4941-b4bb-0973f99f21dd) | ![Screenshot_20240211_122052_YouTube Music](https://github.com/YT-Advanced/ReX-patches/assets/74029985/3dd387ce-1702-41f5-b0c4-85999a06daca) | 
| ![Screenshot_20240211_121647_ReVanced Extended Music](https://github.com/YT-Advanced/ReX-patches/assets/74029985/af4389c8-0e82-4ce0-be9a-66eba0f62642) | ![Screenshot_20240211_122022_ReVanced Extended Music](https://github.com/YT-Advanced/ReX-patches/assets/74029985/9194c2e7-49ad-4dc7-98f8-bb72a472ac38) | ![Screenshot_20240211_122100_YouTube Music](https://github.com/YT-Advanced/ReX-patches/assets/74029985/cd2cd087-de35-4317-92a2-d6ce7d91a4c1) | 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
<img alt="image" src="https://github.com/YT-Advanced/ReX-patches/assets/70064328/6c474d89-9e34-439d-9401-d19380a0e937">

**Comment by Rairof** [comment]
https://github.com/YT-Advanced/ReX-patches/issues/77#issuecomment-1937755996
Also it would be appreciated if you would redirect bug reports to their appropriate repository, i.e https://github.com/YT-Advanced/RVX_BUG_CENTER
👍

**Comment by YT-Advanced** [comment]
> [#77 (comment)](https://github.com/YT-Advanced/ReX-patches/issues/77#issuecomment-1937755996) Also it would be appreciated if you would redirect bug reports to their appropriate repository, i.e https://github.com/YT-Advanced/RVX_BUG_CENTER 👍

Hehe, I think it is better to report there, since I can easier to manager xD
