### ISSUE TITLE
bug: Hide seek message Not working 

### ISSUE THREAD

**Issue by Mehedi5585** [YT-Advanced/ReX-patches#78]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube v.19.04.37

### Bug description

Hide seek message enable, but hide seek message not working 
![IMG_20240211_235903](https://github.com/YT-Advanced/ReX-patches/assets/117540245/bcd33cbf-9da1-47da-824d-27fb37c17201)

### Error logs

```shell
Hide Seek message
```

### Device Environment

Android 12,MIUI 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Hi, can you reproduce the issues and send me the log. Thanks !

Anyway, if you don't know how to debug, feel free to contact me via Telegram.

**Comment by YT-Advanced** [comment]
Done
