### ISSUE TITLE
bug (YT): Cannot change quality if some default is already set.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#80]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v19.04.37

### Bug description

![Screenshot_2024-02-12-14-25-52-65](https://github.com/YT-Advanced/ReX-patches/assets/91815107/545752fe-8b95-48ac-b26d-7e200fb1e01d)

### Error logs

```shell
No logs.
```

### Solution

Just restore the old behaviour.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro.
Android 12.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
Please use https://github.com/YT-Advanced/RVX_BUG_CENTER to post bug reports

**Comment by Aryan-Chauhan** [comment]
> Please use https://github.com/YT-Advanced/RVX_BUG_CENTER to post bug reports

Done.

**Comment by YT-Advanced** [comment]
Fixed in latest version
