### ISSUE TITLE
feat: (youtube shorts) hide "double-tap-to-like animation"

### ISSUE THREAD

**Issue by MondayNitro** [YT-Advanced/ReX-patches#81]
### Application

YouTube

### Feature description

default behaviour in youtube shorts is to show an animation when we double tap the screen to like. i made an empty lottie json which disables this animation.

patch is similar to inotia's **_Hide animated button background_**. the lottie json must replace the existing json file in **_res/raw_** folder.
here is the file:
[like_tap_feedback.json](https://github.com/YT-Advanced/ReX-patches/files/14236524/like_tap_feedback.json)

with animation it looks like:

https://github.com/YT-Advanced/ReX-patches/assets/87489540/31bb51a3-9c62-453b-9385-15297c368331

without animation it looks like:

https://github.com/YT-Advanced/ReX-patches/assets/87489540/8b53a77c-31de-43a2-a2fa-a1c4641ffb3f

### Motivation

the like button already changes appearance on double tapping to like the shorts, so an additional animation for like effect seems redundant. also leads to a cleaner ui, so it can be useful for some users

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Can you attatch the unmodified file too

**Comment by MondayNitro** [comment]
> Can you attatch the unmodified file too

[like_tap_feedback.json](https://github.com/YT-Advanced/ReX-patches/files/14257480/like_tap_feedback.js

all lottie animations are present in res/raw folder of apk

**Comment by YT-Advanced** [comment]
thanks
