### ISSUE TITLE
bug: Rvx builder exit with error

### ISSUE THREAD

**Issue by cedomirvalcic** [YT-Advanced/ReX-patches#82]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Rvx Builder v5.1.0 for Windows
![Screenshot 2024-02-12 100953](https://github.com/YT-Advanced/ReX-patches/assets/30777225/dc2ed30d-9376-4226-8f28-d421badfc205)

![Screenshot 2024-02-12 100119](https://github.com/YT-Advanced/ReX-patches/assets/30777225/2d69239c-9a9d-4a4b-b072-0eebf075d5f6)

### Bug description

When I try to patch with rvx-builder, it comes up with the following error in the screenshot . With Inotia`s original version everything works normally.

### Device Environment

Windows 11 Pro 22H2

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
Please use https://github.com/YT-Advanced/RVX_BUG_CENTER to post bug reports
