### ISSUE TITLE
bug (YT Music) : Custom icon not applying on Splash Screen.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#83]
### Type

Error at runtime

### Tools used

Revancify

### Application

YT Music v6.37.50

### Bug description

I'm using MMT icon but it isn't applying on Splash Screen page. Earlier it used to apply there.
![Screenshot_2024-02-12-09-23-32-41_0eaaacfb1e02f862bb18505a09b95933](https://github.com/YT-Advanced/ReX-patches/assets/91815107/f8608b0b-e615-4769-b4c9-06cc94098307)

### Error logs

```shell
No logs.
```

### Solution

Custom icon should display on splash screen also.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro.
Android 12.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1797#issue-2027726182

**Comment by Aryan-Chauhan** [comment]
> https://github.com/inotia00/ReVanced_Extended/issues/1797#issuecomment-1842163621

I know.

That issue was also created by me.

But it was seriously illogical to remove that feature.

Literally makes no sense.

It likes removing a good feature unnecessarily.

**Comment by Rairof** [comment]
Also https://github.com/YT-Advanced/RVX_BUG_CENTER

**Comment by Aryan-Chauhan** [comment]
> Understood, Also please use https://github.com/YT-Advanced/RVX_BUG_CENTER to post bug reports

Done.

**Comment by girshcatt** [comment]
Bruh this is not a bug, this is behaviour that was explained in 2.203.1 changelog, if you want any feature to be added, just create festure request

**Comment by Aryan-Chauhan** [comment]
> Bruh this is not a bug, this is behaviour that was explained in 2.203.1 changelog, if you want any feature to be added, just create festure request

I already read that changelog many days ago.

This was an unnecessary & illogical change. I'm unable to understand why inotia00 implemented it in the first place.

**Comment by girshcatt** [comment]
> This was an unnecessary & illogical change. I'm unable to understand why inotia00 implemented it in the first place.

Anyway this is not a bug

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because it is fixed in:

https://github.com/anddea/revanced-patches/releases/tag/v2.221.0.2
