### ISSUE TITLE
bug: <Hide seek Message> Not working 

### ISSUE THREAD

**Issue by hphp22f** [YT-Advanced/ReX-patches#85]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube v.19.04.37

### Bug description

Hide seek message is enable,but it's not working 

### Device Environment

Android 13 MIUI14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
https://github.com/YT-Advanced/ReX-patches/issues/78
