### ISSUE TITLE
bug YouTube (KeepLandscapeModePatch): PIP issue when lock/unlock screen

### ISSUE THREAD

**Issue by MarcaDian** [YT-Advanced/ReX-patches#86]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

v19.04.47

### Bug description

Go to **ReVanced Extended** - **Fullscreen** - enable **Keep landscape mode**
Open video, expand to full screen, lock screen, unlock screen, minimize to landscape mode, go to desktop

Result:
PIP displays content below the video player
![Зображення WhatsApp, дата_ 2024-02-13 о 23 53 18_ae26d1af](https://github.com/YT-Advanced/ReX-patches/assets/152095496/286f6352-7c1c-469b-a1ea-86c2e3a0a0eb)

### Device Environment

A12 MIUI 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Any video pls, I still cannot know how to produce this issues

**Comment by YT-Advanced** [comment]
Thanks, I will try to fix it

**Comment by MondayNitro** [comment]
> Thanks, I will try to fix it

bro its not yt issue, it is rom issue bcs yt uses androids built-in pip player, it doesnt have it own pip mode (like newpipe)

**Comment by YT-Advanced** [comment]
hi, today I checked and cannot reproduce this issues in my side, can you share your settings

**Comment by YT-Advanced** [comment]
Hmm, I still can't reproduce this issues. I think I will remove this feature in next release

**Comment by YT-Advanced** [comment]
@WhisperRevanced I know, I have trying to reproduce this issues in all my devices (both virtual and physical devices) and still cannot have this issues, weird.
