### ISSUE TITLE
feat: (youtube shorts) add "overlay buttons for shorts player" patch

### ISSUE THREAD

**Issue by MondayNitro** [YT-Advanced/ReX-patches#88]
### Application

YouTube

### Feature description

a patch that allows for overlay buttons in shorts player; it would be really nice and useful to have copy link, download buttons in shorts.

### Motivation

same as overlay buttons in video player

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Can you share a preview screenshot of the overlay button and how it look like in Shorts player

**Comment by MondayNitro** [comment]
> Can you share a preview screenshot of the overlay button and how it look like in Shorts player

ideally you should add them above the action buttons in shorts like this

![Screenshot_20240216-145724_YouTube](https://github.com/YT-Advanced/ReX-patches/assets/87489540/c3a83b4b-3310-4d76-bc08-3eda54748a03)

if you are able to implement the patch, we could request anddea to design the icons for shorts

**Comment by YT-Advanced** [comment]
Damn, it look... very ugly
