### ISSUE TITLE
feat: add seekbar in PiP

### ISSUE THREAD

**Issue by Rairof** [YT-Advanced/ReX-patches#90]
### Application

YouTube

### Feature description

Video seekbar being available in PiP mode in YouTube. I remember YouTube having an experiment for premium only on it before but removed it after some time. Would be great for users to just seek through the video in PIP without having to open the app in fullscreen to seek it.

Referenced plugin feature picture-
![1707930261982](https://github.com/YT-Advanced/ReX-patches/assets/107706560/bf9c880e-6a5d-4339-ba53-780c504fb776)

### Motivation

I remember YouTube having an experiment for premium only on it before but removed it after some time. Would be great for users to just seek through the video in PIP without having to open the app in Fullscreen to seek it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
Not sure if this is possible to do or not so feel free to close this if its impossible.

**Comment by YT-Advanced** [comment]
Can you share with me exactly which version?

**Comment by Rairof** [comment]
I don't remember anymore, it was long time ago I saw it in YouTube "try out new features" tab

**Comment by Rairof** [comment]
As for the given picture, I edited it with what I remember from that experimental feature

**Comment by sliceanddice9** [comment]
Even adding back & forward seek buttons to PiP would be an improvement.

**Comment by Rairof** [comment]
https://github.com/YT-Advanced/ReX-patches/issues/90#issuecomment-1950265083
I know I can but you wont see the playback then and wont know where you want to stop at so I end up seeking like 2-3 time to land at where I wanted to land, so that's an inconvenient workaround for it.

**Comment by Rairof** [comment]
:/ alright U guess
