### ISSUE TITLE
Bump Support To 19.07.xx

### ISSUE THREAD

**Issue by AbakNacchan** [YT-Advanced/ReX-patches#94]
### Application

YouTube

### Suggestion description

You might want to bump support to 19.07.xx since I don't know why it works like charm on that ver, but got constant crashing on 19.06.xx both in beta or stable ver.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
for 19.06, you have to exclude `Change player flyout panel toggles`
